### ISSUE TITLE
Ctrl+C isn't handled on Windows

### ISSUE THREAD

**Issue by nocturn9x** [japl-lang/japl#10]
When running under windows powershell, the custom signal handler that JAPL sets to catch Ctrl+C events is ignored, and the process just exits. This is especially bad because memory is never freed upon exiting and, when we'll have exceptions, it would disallow us to catch  and raise `InterruptedError`s which can later be handled in the user's code

**Comment by nocturn9x** [comment]
It turns out this error actually happens under any windows terminal, so it's more general than what initially expected

**Comment by ghost** [comment]
Solved with jale. (see PR #42)
