### ISSUE TITLE
The logical operators are broken 

### ISSUE THREAD

**Issue by nocturn9x** [japl-lang/japl#20]
```
JAPL 0.3.0 (alpha, 2020-10-28 20:52:16)
[Nim 1.2.6 on android (arm64)]
=> 2 and 3;
```

This raises the following: 
`
/data/data/com.termux/files/home/japl/src/main.nim(125) main
/data/data/com.termux/files/home/japl/src/main.nim(62) main
/data/data/com.termux/files/home/japl/src/main.nim(53) repl
/data/data/com.termux/files/home/japl/src/vm.nim(609) interpret
/data/data/com.termux/files/home/japl/src/vm.nim(238) run
/data/data/com.termux/files/usr/lib/nim/lib/system/fatal.nim(49) sysFatal
Error: unhandled exception: index 3 not in 0 .. 1 [IndexError]`

This is kind of weird as `or` works and it compiles to very similar instructions. Probably related to #3

**Comment by nocturn9x** [comment]
Update, now apparently `or` is broken too

**Comment by ghost** [comment]
I can't seem to replicate the issue in the current latest commit, probably was just a consequence of some (fixed) deeper error, so closing.
