### ISSUE TITLE
Variable names are misread

### ISSUE THREAD

**Issue by nocturn9x** [japl-lang/japl#25]
This issue is quite weird and hard to reproduce reliably, see attached screenshot for a better understanding of the problem. This is probably related to a read that is carried out too far, but the source of this bug is still unknown

![image](https://user-images.githubusercontent.com/23456189/103409652-02c3cb00-4b68-11eb-8be2-c0eedb6c803b.png)

**Comment by ghost** [comment]
The issue is I believe fixed currently in my fork, so it will be easy to fix it upstream soon.
