### ISSUE TITLE
Chunks are ref objects

### ISSUE THREAD

**Issue by ghost** [japl-lang/japl#38]
types/function.nim defines functions, but they contain chunks, which are GC'd. Ungc'd memory should not contain GC'd objects.

**Comment by nocturn9x** [comment]
I'm actually not sure if the Chunk type needs to be ref or not, since its values are only set once and never read

EDIT: Nevermind, this is trickier than it sounds

EDIT 2: Changing the chunk type from `ref object` to `object` doesn't seem to affect JAPL at all (the test suite still passes)
