### ISSUE TITLE
Killed tests with debug_vm or debug_compiler on

### ISSUE THREAD

**Issue by ghost** [japl-lang/japl#44]
Some tests get killed with these flags on. Possible cause: check whether pipes are okay. Investigate.

**Comment by nocturn9x** [comment]
This is most likely due to the fact that printing all the debugging information to stdout is very resource intensive and slows the test down. We might want to tune the max. amount of ticks a test can run before getting killed

**Comment by nocturn9x** [comment]
Forgot to close this. The max timeout for tests is now a CLI option when running the build script
