### ISSUE TITLE
SetLocals don't work

### ISSUE THREAD

**Issue by ghost** [japl-lang/japl#7]
In common.nim, in the definition of `[]=` for self: CallFrame self.stack[self.getAbsIndex(idx)] = val is used, but the `[]=` syntax is invalid for sequences. This crashes the REPL on every SetLocal call.

**Comment by ghost** [comment]
Might be #5 in disguise.
since `[]=` need to refer to indexes that exist, but so does SetLocal actually

**Comment by nocturn9x** [comment]
Update, see `src/frame.nim` instead
